services:
  mention-bot:
    build: .
    container_name: mention-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database.sqlite3:/app/database.sqlite3
      - ./logs.log:/app/logs.log
    ports:
      - "8001:8001"
    networks:
      - monitoring_system

networks:
  monitoring_system:
    external: true